### ISSUE TITLE
Handle out of stock items

### ISSUE THREAD

**Issue by mark-thompson** [mark-thompson/whole-foods-deliverance#2]
Navigating to the slot selection page occasionally fails due to an out of stock alert for one of the items in cart. This may also affect slot page refreshes.
Could handle this with a user alert and await input, or add a flag to ignore and continue

**Comment by b3nw** [comment]
Keep missing slots due to the handling out of stock items, would be good to add a flag to ignore and continue.

```
INFO:__main__:Checking for available slots
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/element {"using": "css selector", "value": ".ufss-slotselect-container"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "POST /session/634e69c8b35495cc72a56fdfd6b9939b/element HTTP/1.1" 404 1061
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
ERROR:utils:Timed out waiting for target element: ('class name', 'ufss-slotselect-container')
INFO:utils:Dumping page source to: source_dump_1586741431025.html
DEBUG:selenium.webdriver.remote.remote_connection:GET http://127.0.0.1:59393/session/634e69c8b35495cc72a56fdfd6b9939b/source {}
DEBUG:urllib3.connectionpool:http://127.0.0.1:59393 "GET /session/634e69c8b35495cc72a56fdfd6b9939b/source HTTP/1.1" 200 107899
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
Traceback (most recent call last):
  File ".\run.py", line 178, in <module>
    main_loop(driver, args)
  File ".\run.py", line 135, in main_loop
    slots = slots_available(driver, slot_prefs)
  File ".\run.py", line 73, in slots_available
    slots = get_slots(driver)
  File ".\run.py", line 31, in get_slots
    slot_container = get_element(driver, config.Locators.SLOT_CONTAINER)
  File "C:\Users\b3nw\Documents\whole-foods\whole-foods-deliverance\utils.py", line 55, in get_element
    WebDriverWait(driver, timeout).until(
  File "C:\Users\b3nw\Documents\whole-foods\whole-foods-deliverance\env\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by mark-thompson** [comment]
@b3nw Agreed. Could you upload the full or partial HTML from `source_dump_1586741431025.html` somewhere (redact any personal information, of course) so I can look into how best to achieve this?
I haven't been able to get my hands on the source for that alert page

**Comment by ghost** [comment]
@mark-thompson Here is the dump file source_dump_1586908512545.html for this use case. I had to change the extension of the file to make github happy. Thanks.

[source_dump_1586908512545.txt](https://github.com/mark-thompson/whole-foods-deliverance/files/4477450/source_dump_1586908512545.txt)

**Comment by b3nw** [comment]
Yup attached. 

[source_dump_1586741431025.txt](https://github.com/mark-thompson/whole-foods-deliverance/files/4478614/source_dump_1586741431025.txt)

**Comment by mark-thompson** [comment]
@b3ll0v1c @b3nw Try pulling the most recent version and run with the `ignore-oos` option. This worked for me in testing, but let me know how it goes

**Comment by mark-thompson** [comment]
Closing this as I encountered the OOS alert 'in the wild' and it was handled
