### ISSUE TITLE
timeout error?

### ISSUE THREAD

**Issue by banittles** [mark-thompson/whole-foods-deliverance#20]
ERROR: Timed out waiting for target element: ('class name', 'ufss-slotselect-container')
Traceback (most recent call last):
  File "run.py", line 185, in <module>
    main_loop(driver, args)
  File "run.py", line 141, in main_loop
    slots = slots_available(driver, slot_prefs)
  File "run.py", line 76, in slots_available
    slots = get_slots(driver)
  File "run.py", line 30, in get_slots
    slot_container = get_element(driver, config.Locators.SLOT_CONTAINER)
  File "/Users/BD/whole-foods-deliverance/utils.py", line 55, in get_element
    WebDriverWait(driver, timeout).until(
  File "/Users/BD/whole-foods-deliverance/env/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by mark-thompson** [comment]
Was this the first time it got to the slot select page, or did this happen mid-run after refreshing?
If the former, there's an open issue (#19) for multiple delivery type slot pages that look like this:
<img width="529" alt="Screen Shot 2020-04-14 at 6 08 57 PM" src="https://user-images.githubusercontent.com/7841836/79279106-4744f480-7e7b-11ea-84a1-78c3f38b8ff9.png">

**Comment by banittles** [comment]
happened mid run while refreshing for slots

my area doesnt get 3 days, just "today" and "tomorrow"

**Comment by mark-thompson** [comment]
@banittles Ah gotcha. Did you happen to see if the page looked any different than normal when you noticed the error?
That error means you were either redirected to another page, or it took longer than ~5s to load the slot page.
Try running with the `--debug` flag next time. If you encounter that error again, the page source will be saved and you can upload here

**Comment by banittles** [comment]
caught it last night, looks like amazon defaults to a different page sometimes after a refresh. "check out these other items..." type of deal.

just got this error when it found a slot though...

INFO: Found 1 slots: 
Today::By 4:00 PM
[2020-04-15 11:00:50] {alert} INFO: Alerting user with message: 'Delivery slots found'
[2020-04-15 11:00:50] {wrapper} ERROR: send_sms() requires a config file at 'conf.toml' with key 'twilio'
[2020-04-15 11:00:50] {wrapper} ERROR: send_telegram() requires a config file at 'conf.toml' with key 'telegram'
[2020-04-15 11:00:50] {main_loop} INFO: Attempting to select slot and checkout
[2020-04-15 11:00:50] {main_loop} INFO: Selecting slot: Today::By 4:00 PM
[2020-04-15 11:00:51] {navigate} INFO: Navigating <Route beginning at 'https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html' with 3 stops>
[2020-04-15 11:00:51] {navigate_waypoint} INFO: Navigating <Waypoint ('xpath', "//*[contains(@class, 'ufss-overview-continue-button')]") -> 'gp/buy/payselect/handlers/display.html'>
[2020-04-15 11:01:02] {navigate} WARNING: Current URL 'https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html' does not match target
Handling possible redirect (timeout in 20s)
[2020-04-15 11:01:22] {navigate} ERROR: Timed out waiting for redirect to a valid dest
Current URL: 'https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1'
Traceback (most recent call last):
  File "/Users/BD/whole-foods-deliverance/nav.py", line 96, in navigate
    WebDriverWait(driver, timeout).until(
  File "/Users/BD/whole-foods-deliverance/env/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 185, in <module>
    main_loop(driver, args)
  File "run.py", line 155, in main_loop
    build_route(site_config, 'CHECKOUT').navigate(driver)
  File "/Users/BD/whole-foods-deliverance/nav.py", line 104, in navigate
    raise e
  File "/Users/BD/whole-foods-deliverance/nav.py", line 78, in navigate
    self.navigate_waypoint(driver, waypoint, timeout)
  File "/Users/BD/whole-foods-deliverance/nav.py", line 59, in navigate_waypoint
    raise NavigationException(
nav.NavigationException: Message: Navigation to 'gp/buy/payselect/handlers/display.html' failed

**Comment by banittles** [comment]
i was running with auto checkout, trying it again without auto checkout

**Comment by mark-thompson** [comment]
@banittles Try running now with the newest version - this kind of redirect should be handled

**Comment by mark-thompson** [comment]
@banittles closing this as it appears to be resolved
